# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  IMAGE_NAME: custom-nginx
  TAG: $(Build.BuildId)

# Link the variable group
variables:
- group: hkbu-uat-registry-creds

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Logging into ACR using username/password..."
    echo $(ACR_PASSWORD) | docker login $(ACR_LOGIN_SERVER) -u $(ACR_USERNAME) --password-stdin
  displayName: 'Login container registry'

