version: '3.8'

services:
  custom-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom-nginx-server
    ports:
      - "8080:80"
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

volumes:
  nginx-logs: 